Added code for TiesPropose procedure and favourite neighbour
rawatamit/GraphMatching pull request #13
Opened 2023-11-21 04:06 UTC by meghanasoni

2023-11-21 15:24 UTC, rawatamit requested changes

2023-11-21 15:24 UTC, rawatamit commented on include/PreferenceList.h
> +enum PreferenceOrderT { cEqual=0, cBetter, cWorse };
Indentation should be:
enum PreferenceOrderT {
  cEqual=0,
  cBetter,
  cWorse
};

2023-11-21 15:24 UTC, rawatamit commented on lib/MatchingAlgorithm.cc
> +      if (y < t || ((y == t || (y == t && star)) && preference == cBetter)) {
Complex statements should be wrapped in round braces, like (y==t) and (preference == cBetter)

2023-11-21 15:24 UTC, rawatamit commented on lib/MatchingAlgorithm.cc
> +      if (y < t || (y == t && (preference == cEqual|| preference == cBetter)) || (y == t && star && preference == cBetter)) {
Wrap complex statements in round braces, and consider defining booleans to simplify the if.
For e.g.
bool isBetter = (preference == cBetter);
bool isBetterOrEqual = (isBetter || (preference == cEqual));

2023-11-21 15:24 UTC, rawatamit commented on lib/PreferenceList.cc
> +  // Return 0 if rank of a1 = rank of a2
These comments need to be updated.

2023-11-21 15:26 UTC, rawatamit requested changes

2023-11-21 15:26 UTC, rawatamit commented on test/TestPrefers.cc
> +    auto G = read_graph(get_filepath(get_resources_dir(), "/weak_stable.txt")); // required only for critical RSM constructor, doesn't affect output of the function
Put this comment before the code in its own line.
Its not completely necessary, but wrap the lines to 80 column width.

2023-11-21 15:26 UTC, rawatamit commented on test/TestFavouriteNeighbour.cc
> +    auto G = read_graph(get_filepath(get_resources_dir(), "/weak_stable.txt")); // required only for critical RSM constructor, doesn't affect output of the function
Comment should go in its own line.

2023-11-21 15:26 UTC, rawatamit commented on test/TestFavouriteNeighbour.cc
> +    std::shared_ptr<Vertex> dummy = std::make_shared<Vertex>("d"); // dummy partner for all matched vertices
Comment on own line.

2023-11-21 15:26 UTC, rawatamit commented on test/TestFavouriteNeighbour.cc
> +    auto G = read_graph(get_filepath(get_resources_dir(), "/weak_stable.txt")); // required only for critical RSM constructor, doesn't affect output of the function
Comment before the code line.

2023-11-21 15:27 UTC, rawatamit requested changes

2023-11-21 15:27 UTC, rawatamit commented on include/VertexBookkeeping.h
> +    bool star;
This variable should be documented with the use, and also the place where it is updated.

2023-11-21 15:27 UTC, rawatamit reviewed
What does this commit merge?

2023-12-14 13:42 UTC, meghanasoni commented
It merges the code for TiesPropose and CriticalPropose methods in the criticalRSM class and NProposingTiesMatching to compute weak stable matching with ties(which is basically the output when there are no critical vertices). I will update the criticalRSM method by using all these functions after they are merged

2023-12-18 14:15 UTC, rawatamit approved these changes

2023-12-18 14:16 UTC, merged